### ISSUE TITLE
Restore archipelago tests (and test-app)

### ISSUE THREAD

**Issue by hugoArregui** [decentraland/archipelago-service#8]

**Comment by juanscolari** [comment]
ℹ️ The `test-app` uses the legacy `lighthouse` endpoint `comms/layers/{layerId}`, so it won't be implemented for the moment.

**Comment by juanscolari** [comment]
Removed some smoke tests and a fixture that was not working with Jest (instead of Mocha): https://github.com/decentraland/archipelago-service/commit/fad8029b7f905e1adcda5f13ee5633b36378e0dc
